### ISSUE TITLE
Value converter is not firing

### ISSUE THREAD

**Issue by bj0** [michael-damatov/lambda-converters#4]
I have the following lambda converter:

        public static readonly IValueConverter SignalStrengthImage = ValueConverter.Create<int, string>(e =>
        {
            logger.Info("wtf");
            var root = "pack://application:,,,/MyLibrary;component";
            var path = $"{root}/assets/signal_strength_unknown.png";
            switch ((int)e.Value)
            {
                case 0: path = $"{root}/assets/signal_strength_0.png"; break;
                case int n when n <= 20: path = $"{root}/assets/signal_strength_20.png"; break;
                case int n when n <= 40: path = $"{root}/assets/signal_strength_40.png"; break;
                case int n when n <= 60: path = $"{root}/assets/signal_strength_60.png"; break;
                case int n when n <= 80: path = $"{root}/assets/signal_strength_80.png"; break;
                default: path = $"{root}/assets/signal_strength_100.png"; break;
            }
            return path;
        });

With the corresponding xaml:

        <Image Source="{Binding Status.SignalStrength, Converter={x:Static c:Converters.SignalStrengthImage}, FallbackValue={StaticResource UnknownSignalStrength}}" Width="70" Height="70"/>

Unfortunately, the converter seems as though it is never called.  When the property on the viewmodel is updated, the Image goes from displaying the fallback image to displaying nothing.  The log statement in the converter is never fired, and if I set a breakpoint it is never reached.  

If I create a normal IValueConverter class the traditional way, with the exact same code, it works properly.

**Comment by Yeah69** [comment]
Is the property `Status.SignalStrength` of type `int`/`Int32`?

**Comment by bj0** [comment]
Yes, I found the problem, in `Converter`, there's an `IsAssignable` check on `targetType`.  Normally this makes sense, but the case of `Source` on `<Image` is different.  The type is `ImageSource` but if you pass in a `string` that is a path to a resource image, the property handles it correctly.
